Repository nimblehq/rails-templates, pull requests merged in 2018-11, with the labels that each got.

#70 Fix generating the template with URL is NOT working.
  rails_docker.rb
Labels: priority : high, type : bug

#72 Remove the mapping port on docker-compose on test environment.
  rails_docker/docker-compose.test.yml
Labels: priority : normal, type : bug

#74 Upgrading Ruby
  rails_docker.rb
  rails_docker/Dockerfile
  rails_docker/Gemfile.txt
Labels: priority : normal, type : feature

#75 Upgrading Rails
  rails_docker/Gemfile.txt
Labels: priority : high, type : improvement

#78 Release - 3.1.0
  LICENSE
  README.md
  rails_docker.rb
  rails_docker/.env
  rails_docker/.env.test
  rails_docker/Dockerfile
  rails_docker/Gemfile.txt
  rails_docker/docker-compose.test.yml
  rails_docker/docker-compose.yml
  rails_docker/start.sh
  shared/app/assets/stylesheets/functions/_sizing.scss
Labels: type : release
