Repository nimblehq/rails-templates, pull requests merged in 2019-04, with the labels that each got.

#82 Fix missing RuboCop disabled comments in disabled animation file.
  shared/rspec/support/disable_animation.rb
Labels: priority : normal, type : bug

#83 Fix missing Redis configuration on Docker compose file.
  rails_docker/docker-compose.dev.yml
  rails_docker/docker-compose.yml
Labels: priority : normal, type : bug

#87 Set wait_on_first_by_default to true
  shared/rspec/support/capybara.rb
Labels: status : wip, type : improvement

#88 Update Rails from 5.1.6 to 5.2.3
  README.md
  rails_docker.rb
  rails_docker/Gemfile.txt
  shared/app/assets/javascripts/application.js
Labels: priority : high, type : improvement

#91 Initialize assets folder structure
  rails_docker.rb
  shared/app/assets/javascripts/adapters/.keep
  shared/app/assets/javascripts/components/.keep
  shared/app/assets/javascripts/config/.keep
  shared/app/assets/javascripts/helpers/.keep
  shared/app/assets/javascripts/initializers/.keep
  shared/app/assets/javascripts/lib/.keep
  shared/app/assets/javascripts/screens/.keep
  shared/app/assets/stylesheets/application.scss
  shared/app/assets/stylesheets/base/.keep
  shared/app/assets/stylesheets/components/.keep
  shared/app/assets/stylesheets/layouts/.keep
  shared/app/assets/stylesheets/mixins/.keep
  shared/app/assets/stylesheets/screens/.keep
  shared/app/assets/stylesheets/variables.scss
Labels: priority : normal, type : improvement

#90 Fix errors when building the docker image
  rails_docker/Dockerfile
Labels: priority : high, type : bug

#92 Update ruby version from 2.5.3 to 2.6.2
  README.md
  rails_docker.rb
  rails_docker/Dockerfile
  rails_docker/Gemfile.txt
Labels: priority : normal, type : chore

#94 Update database config
  shared/config/application.yml
  shared/config/database.yml
Labels: priority : normal, type : chore

#93 Cleanup gems
  rails_docker.rb
  rails_docker/Gemfile.txt
  shared/app/assets/javascripts/application.js
  shared/rspec/codebase/codebase_spec.rb
  shared/rspec/support/capybara.rb
  shared/rspec/support/json_matchers.rb
Labels: priority : normal, type : chore

#95 Update secret key base configuration due to rails 5.2 changes
  rails_docker/docker-compose.yml
  shared/config/application.yml
Labels: priority : high, type : chore

#96 Add Rack Deflater to reduce response size
  rails_docker.rb
Labels: priority : normal, type : improvement

#98 Enable Bullet to watch for N+1 queries
  lib/bullet.rb
  rails_docker.rb
  shared/rspec/support/bullet.rb
Labels: priority : normal, type : chore

#100 Setup gitignore
  rails_docker.rb
Labels: priority : low, type : chore

#101 Setup editorconfig
  rails_docker.rb
  shared/.editorconfig
Labels: priority : low, type : chore

#99 Replace chromedriver-helper with webdrivers
  rails_docker/Dockerfile
  rails_docker/Gemfile.txt
  shared/rspec/support/webdrivers.rb
Labels: priority : normal, type : chore

#102 Update chrome install script
  rails_docker/Dockerfile
Labels: priority : low, type : chore

#105 Release/v3.2.0
  README.md
  lib/bullet.rb
  lib/i18n.rb
  rails_docker.rb
  rails_docker/Dockerfile
  rails_docker/Gemfile.txt
  rails_docker/docker-compose.dev.yml
  rails_docker/docker-compose.yml
  shared/.editorconfig
  shared/app/assets/javascripts/adapters/.keep
  shared/app/assets/javascripts/application.js
  shared/app/assets/javascripts/components/.keep
  shared/app/assets/javascripts/config/.keep
  shared/app/assets/javascripts/helpers/.keep
  shared/app/assets/javascripts/initializers/.keep
  shared/app/assets/javascripts/initializers/i18n.js
  shared/app/assets/javascripts/initializers/index.js
  shared/app/assets/javascripts/lib/.keep
  shared/app/assets/javascripts/screens/index.js
  shared/app/assets/stylesheets/application.scss
  shared/app/assets/stylesheets/base/.keep
  shared/app/assets/stylesheets/components/.keep
  shared/app/assets/stylesheets/layouts/.keep
  shared/app/assets/stylesheets/mixins/.keep
  shared/app/assets/stylesheets/screens/.keep
  shared/app/assets/stylesheets/variables.scss
  shared/app/controllers/concerns/localization.rb
  shared/config/application.yml
  shared/config/database.yml
  shared/config/i18n-js.yml
  shared/rspec/codebase/codebase_spec.rb
  shared/rspec/support/bullet.rb
  shared/rspec/support/disable_animation.rb
  shared/rspec/support/json_matchers.rb
  shared/rspec/support/webdrivers.rb
Labels: type : release
