Repository nimblehq/rails-templates, pull requests merged in 2019-11, with the labels that each got.

#122 Add the @nimbl3/eslint-config-nimbl3 to package.json file
  rails_docker.rb
  shared/.npmrc
  shared/app/assets/stylesheets/functions/_sizing.scss
  shared/linters/.eslintignore
  shared/linters/.eslintrc
Labels: priority : high, type : chore

#116 Upgrade to Rails 6 and Ruby 2.6.5
  README.md
  lib/i18n.rb
  rails_docker.rb
  rails_docker/Dockerfile
  rails_docker/Gemfile.txt
  shared/.npmrc
  shared/Procfile.dev
  shared/README.md
  shared/app/assets/javascripts/initializers/index.js
  shared/app/assets/stylesheets/functions/_sizing.scss
  shared/app/javascript/adapters/.keep
  shared/app/javascript/components/.keep
  shared/app/javascript/config/.keep
  shared/app/javascript/helpers/.keep
  shared/app/javascript/initializers/.keep
  shared/app/javascript/initializers/i18n.js
  shared/app/javascript/initializers/index.js
  shared/app/javascript/lib/.keep
  shared/app/javascript/screens/index.js
  shared/config/i18n-js.yml
  shared/linters/.eslintignore
  shared/linters/.eslintrc
  shared/linters/.rubocop.yml
  shared/rspec/support/webdrivers.rb
Labels: priority : normal, type : feature

#132 Upgrade to Rails 6.0.1
  rails_docker/Gemfile.txt
Labels: priority : normal, type : feature

#136 Do not fallback to the Sprockets server when the precompiled asset is missing on Test env
  rails_docker.rb
  shared/rspec/support/assets.rb
Labels: type : chore

#137 Remove sidekiq default fake mode for testing line
  shared/rspec/support/sidekiq.rb
Labels: type : chore
