Repository nimblehq/rails-templates, pull requests merged in 2020-06, with the labels that each got.

#186 [Chore] Rename makefile name and respect makefile tab indent style
  .editorconfig
  Makefile
Labels: type : improvement

#184 Replace link to shared ESLint with the new NPMJS organization
  .template/spec/variants/web/package_json_spec.rb
  .template/variants/web/.eslintrc
  .template/variants/web/package.json.rb
Labels: priority : high, type : chore

#187 Release - 4.1.0
  .editorconfig
  .pronto.yml.tt
  .semaphore/semaphore.yml
  .template/addons/docker/.dockerignore.tt
  .template/addons/docker/.env.tt
  .template/addons/docker/Dockerfile.tt
  .template/addons/docker/docker-compose.yml.tt
  .template/addons/docker/template.rb
  .template/addons/semaphore/.semaphore/README.md.tt
  .template/addons/semaphore/.semaphore/promotion-production.yml.tt
  .template/addons/semaphore/.semaphore/promotion-staging.yml.tt
  .template/addons/semaphore/.semaphore/semaphore.yml.tt
  .template/addons/semaphore/Dockerfile.web.tt
  .template/addons/semaphore/Dockerfile.worker.tt
  .template/addons/semaphore/template.rb
  .template/lib/template/errors.rb
  .template/spec/addons/semaphore/template_spec.rb
  .template/spec/base/bin/template_spec.rb
  .template/spec/base/config/environments/development_spec.rb
  .template/spec/base/config/environments/production_spec.rb
  .template/spec/base/config/environments/test_spec.rb
  .template/spec/variants/web/config/webpack/template_spec.rb
  .template/spec/variants/web/package_json_spec.rb
  .template/spec/variants/web/spec/template_spec.rb
  .template/variants/api/template.rb
  .template/variants/web/.eslintrc
  .template/variants/web/Gemfile.rb
  .template/variants/web/app/template.rb
  .template/variants/web/config/webpack/template.rb
  .template/variants/web/package.json.rb
  .template/variants/web/spec/support/webpack.rb
  .template/variants/web/spec/systems/.keep
  .template/variants/web/spec/template.rb
  .template/variants/web/template.rb
  Makefile
  README.md
  README.md.tt
  bin/docker-prepare
  bin/template.rb
  template.rb
Labels: type : release
