Repository nimblehq/rails-templates, pull requests merged in 2020-03, with the labels that each got.

#175 Add Github PR template
  .template/addons/docker/.dockerignore.tt
  template.rb
Labels: priority : normal, type : feature

#174 Optimize Dockerfile
  .template/addons/docker/Dockerfile.tt
Labels: priority : normal, type : improvement

#163 Integrate with Semaphore 2
  .semaphore/semaphore.yml
Labels: priority : normal, type : feature

#177 Semaphore CI 2.0 Addon
  .pronto.yml.tt
  .template/addons/docker/.dockerignore.tt
  .template/addons/docker/.env.tt
  .template/addons/docker/Dockerfile.tt
  .template/addons/docker/docker-compose.yml.tt
  .template/addons/semaphore/.semaphore/README.md.tt
  .template/addons/semaphore/.semaphore/promotion-production.yml.tt
  .template/addons/semaphore/.semaphore/promotion-staging.yml.tt
  .template/addons/semaphore/.semaphore/semaphore.yml.tt
  .template/addons/semaphore/Dockerfile.web.tt
  .template/addons/semaphore/Dockerfile.worker.tt
  .template/addons/semaphore/template.rb
  .template/spec/addons/semaphore/template_spec.rb
  .template/spec/variants/web/spec/template_spec.rb
  .template/variants/web/spec/systems/.keep
  .template/variants/web/spec/template.rb
  README.md.tt
  template.rb
Labels: priority : normal, type : feature

#160 Webpack on test
  .template/spec/variants/web/config/webpack/template_spec.rb
  .template/spec/variants/web/spec/template_spec.rb
  .template/variants/web/config/webpack/template.rb
  .template/variants/web/spec/support/webpack.rb
  .template/variants/web/spec/template.rb
  README.md
Labels: priority : normal, type : improvement

#178 Enable single template application
  .template/addons/docker/template.rb
  .template/addons/semaphore/template.rb
  .template/spec/base/config/environments/development_spec.rb
  .template/spec/base/config/environments/production_spec.rb
  .template/spec/base/config/environments/test_spec.rb
  .template/variants/api/template.rb
  .template/variants/web/Gemfile.rb
  .template/variants/web/app/template.rb
  .template/variants/web/template.rb
  README.md
  template.rb
Labels: priority : normal, type : feature

#179 Add support old applications to apply the template
  .template/lib/template/errors.rb
  .template/variants/web/app/template.rb
  .template/variants/web/template.rb
  template.rb
Labels: priority : normal, type : chore

#180 Add script to copy the gem dependencies for building docker image
  .template/addons/docker/.dockerignore.tt
  .template/addons/docker/Dockerfile.tt
  .template/addons/semaphore/.semaphore/promotion-production.yml.tt
  .template/addons/semaphore/.semaphore/promotion-staging.yml.tt
  .template/addons/semaphore/.semaphore/semaphore.yml.tt
  .template/spec/base/bin/template_spec.rb
  bin/docker-prepare
  bin/template.rb
  makefile
Labels: priority : normal, type : improvement
