Repository nimblehq/rails-templates, pull requests merged in 2020-08, with the labels that each got.

#189 Upgrade to Ruby 2.7.1 and Rails 6.0.3.2
  .rubocop.yml
  .semaphore/semaphore.yml
  .template/Gemfile.lock
  Gemfile.tt
  README.md
  template.rb
Labels: priority : normal, type : chore

#190 Prepare webpack assets only if there is at least one system test
  .template/variants/web/spec/support/webpack.rb
Labels: priority : normal, type : improvement

#193 [CHORE] Refactor Dockerfile template
  .template/addons/docker/Dockerfile.tt
Labels: priority : normal, type : chore, type : improvement

#199 Fixing rubocop issue in disable_animation.rb
  .template/variants/web/spec/support/disable_animation.rb
Labels: priority : high, type : chore

#143 Add sanitize helper in the spec
  .template/spec/variants/web/spec/template_spec.rb
  .template/variants/web/spec/support/sanitize.rb
Labels: priority : normal, type : chore

#195 Replace pronto with danger
  .gitignore.rb
  .pronto.yml.tt
  .reek.yml
  .semaphore.yml
  .template/addons/docker/docker-compose.test.yml.tt
  .template/spec/base/template_spec.rb
  .template/spec/variants/web/dangerfile_spec.rb
  .template/spec/variants/web/gemfile_spec.rb
  .template/spec/variants/web/template_spec.rb
  .template/variants/web/.pronto_eslint_npm.yml
  .template/variants/web/Dangerfile.rb
  .template/variants/web/Gemfile.rb
  .template/variants/web/template.rb
  Dangerfile
  Gemfile.tt
  README.md.tt
  config.reek
  template.rb
Labels: priority : high, type : feature

#209 Adding Engine prefix name validator
  spec/codebase/codebase_spec.rb
  spec/template.rb
Labels: priority : normal, type : improvement

#215 Forcing the ruby template version
  template.rb
Labels: priority : normal, type : improvement

#212 Remove the spec/template.rb in the new app
  spec/template.rb
Labels: priority : high, type : bug

#206 Enable --parallel on rubocop
  spec/codebase/codebase_spec.rb
Labels: priority : normal, type : improvement

#197 Upgrade Webpacker
  .template/variants/web/Gemfile.rb
Labels: priority : normal, type : chore

#201 Enable core-js
  .template/spec/variants/web/app/template_spec.rb
  .template/variants/web/app/template.rb
Labels: priority : normal, type : feature

#198 Enable FrozenStringLiteralComment
  .rubocop.yml
  .template/hooks/before_complete/template.rb
  template.rb
Labels: priority : normal, type : chore

#208 Moving rspec-rails to development and test group
  Gemfile.tt
Labels: priority : normal, type : chore

#207 Adding .nvmrc file
  .template/addons/docker/Dockerfile.tt
  .template/spec/variants/web/template_spec.rb
  .template/variants/web/.nvmrc.tt
  .template/variants/web/template.rb
  template.rb
Labels: priority : normal, type : chore
