Repository nimblehq/rails-templates, pull requests merged in 2020-10, with the labels that each got.

#246 Adding rubocop-rspec
  .rubocop.yml
  Gemfile.tt
  spec/codebase/codebase_spec.rb
Labels: priority : high

#247 Feature/adding rubocop performance
  .rubocop.yml
  .template/variants/web/spec/support/capybara.rb
  .template/variants/web/spec/support/disable_animation.rb
  Gemfile.tt
Labels: priority : high

#243 Only run asset precompile on system test
  .template/variants/web/spec/support/assets.rb
Labels: priority : high

#242 Allow Rails serve static files as default
  .template/spec/base/config/environments/production_spec.rb
  config/environments/production.rb
Labels: priority : high

#229 Integrate danger-simplecov_json
  .template/addons/docker/docker-compose.test.yml.tt
  Dangerfile
  Gemfile.tt
  spec/support/simplecov.rb
Labels: priority : high, type : improvement

#230 Add rails-controller-testing to Gemfile template
  Gemfile.tt
Labels: type : chore

#233 Update backtrace_silencers.rb
  .template/spec/base/config/initializers/backtrace_silencers_spec.rb
  config/initializers/backtrace_silencers.rb
  template.rb
Labels: priority : high

#248 Update Template test
  .semaphore/semaphore.yml
  .template/spec/addons/base/docker/template_spec.rb
  .template/spec/addons/base/semaphore/template_spec.rb
  .template/spec/addons/variants/api/.keep
  .template/spec/addons/variants/web/.keep
  Makefile
  README.md
Labels: priority : high

#231 PhraseApp Addon
  .template/addons/phrase_app/.phraseapp.yml
  .template/addons/phrase_app/spec/codebase/codebase_spec.rb
  .template/addons/phrase_app/spec/template.rb
  .template/addons/phrase_app/template.rb
  .template/spec/addons/base/phrase_app/template.rb
  Makefile
  README.md
  template.rb
Labels: priority : high

#239 Add Bootstrap addon feature
  .semaphore/semaphore.yml
  .template/addons/bootstrap/application.js.rb
  .template/addons/bootstrap/application.scss.rb
  .template/addons/bootstrap/javascript/bootstrap/index.js
  .template/addons/bootstrap/package.json.rb
  .template/addons/bootstrap/stylesheets/bootstrap/bootstrap.scss.tt
  .template/addons/bootstrap/template.rb
  .template/spec/addons/variants/web/.keep
  .template/spec/addons/variants/web/bootstrap/application_js_spec.rb
  .template/spec/addons/variants/web/bootstrap/application_scss_spec.rb
  .template/spec/addons/variants/web/bootstrap/package_json_spec.rb
  .template/variants/web/template.rb
  Makefile
  README.md
Labels: priority : high, type : feature

#237 Add Slim add-on
  .template/addons/slim/Dangerfile.rb
  .template/addons/slim/Gemfile.rb
  .template/addons/slim/template.rb
  .template/spec/addons/variants/web/slim/dangerfile_spec.rb
  .template/spec/addons/variants/web/slim/gemfile_spec.rb
  .template/variants/web/template.rb
  Makefile
  README.md
Labels: priority : high, type : feature

#241 Improve the localization concern, moving to around_action
  .template/spec/base/app/controllers/concerns/localization_spec.rb
  .template/spec/base/config/environments/production_spec.rb
  .template/variants/api/app/controllers/concerns/localization.rb
  .template/variants/web/app/controllers/concerns/localization.rb
  config/application.yml.tt
  config/environments/production.rb
Labels: priority : high

#232 Nginx addon
  .template/addons/nginx/bin/start.sh
  .template/addons/nginx/bin/template.rb
  .template/addons/nginx/config/environments/production.rb
  .template/addons/nginx/config/nginx/api/app.conf.template.tt
  .template/addons/nginx/config/nginx/web/app.conf.template.tt
  .template/addons/nginx/config/template.rb
  .template/addons/nginx/docker.rb
  .template/addons/nginx/template.rb
  .template/addons/semaphore/.semaphore/semaphore.yml.tt
  .template/spec/addons/base/nginx/template_spec.rb
  .template/spec/addons/variants/api/.keep
  .template/spec/addons/variants/api/nginx/template_spec.rb
  .template/spec/addons/variants/web/nginx/template_spec.rb
  .template/spec/base/config/environments/production_spec.rb
  .template/variants/api/app/controllers/concerns/localization.rb
  .template/variants/web/app/controllers/concerns/localization.rb
  Makefile
  README.md
  template.rb
Labels: priority : high

#253 Minor refactor Nginx addon
  .template/addons/nginx/config/nginx/api/app.conf.template.tt
  .template/addons/nginx/config/nginx/app.conf.template.tt
  .template/addons/nginx/config/template.rb
Labels: priority : high

#254 Add github issue templates
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
Labels: type : chore

#255 Add danger plugin danger-undercover
  .semaphore.yml
  Dangerfile
  Gemfile.tt
  spec/support/simplecov.rb
Labels: type : feature

#258 Release/4.2.1
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .semaphore.yml
  Dangerfile
  Gemfile.tt
  spec/support/simplecov.rb
Labels: type : release
