Repository nimblehq/rails-templates, pull requests merged in 2020-09, with the labels that each got.

#222 Fix Rubocop offense when first use template
  .rubocop.yml
  spec/support/vcr.rb
Labels: priority : low, type : chore

#226 Fix missing gems when running app with docker
  .template/addons/docker/Dockerfile.tt
Labels: priority : high, type : bug

#219 Remove redundant IrresponsibleModule smell in Reek config
  .reek.yml
Labels: priority : low, type : chore

#228 Fix error when applying an addon to existing project
  template.rb
Labels: type : bug

#182 Add precompiling assets script to fix docker build
  .template/addons/docker/Dockerfile.tt
  bin/docker-assets-precompile
  bin/template.rb
  config/application.yml.tt
Labels: priority : high, type : improvement
