Repository nimblehq/rails-templates, pull requests merged in 2020-02, with the labels that each got.

#142 Upgrade Node JS version to 12
  rails_docker/Dockerfile
Labels: priority : high, type : chore

#140 Update rubocop.yml and add rubocop-rails
  rails_docker/Gemfile.txt
  shared/linters/.rubocop.yml
  shared/rspec/rails_helper.rb
  shared/rspec/support/assets.rb
  shared/rspec/support/capybara.rb
Labels: priority : normal, type : chore

#138 Add pry-byebug gem for step by step debugging and stack navigation
  rails_docker/Gemfile.txt
Labels: type : feature

#139 Adding default_url_options
  shared/app/controllers/concerns/localization.rb
Labels: priority : high, type : chore

#144 Check exit status code rather than stdout message
  shared/rspec/codebase/codebase_spec.rb
Labels: priority : normal, type : improvement

#145 Use the latest stable web driver version for Selenium as default
  shared/rspec/support/webdrivers.rb
Labels: priority : high, type : chore

#150 Fix the template test
  .tool-versions
  lib/rspec.rb
  shared/linters/.rubocop.yml
  shared/rspec/rails_helper.rb
  shared/rspec/support/disable_animation.rb
Labels: priority : high

#151 Add missing configurations
  lib/config.rb
  rails_docker.rb
Labels: priority : normal

#152 Replace the app_name string replacing to a template (.tt)
  lib/config.rb
  lib/linter.rb
  rails_docker.rb
  rails_docker/.env.tt
  rails_docker/.ruby-gemset.tt
  rails_docker/.ruby-version.tt
  rails_docker/Dockerfile.tt
  rails_docker/Gemfile.tt
  rails_docker/bin/envsetup.sh
  rails_docker/bin/start.sh
  rails_docker/bin/test.sh
  rails_docker/docker-compose.dev.yml.tt
  rails_docker/docker-compose.test.yml.tt
  rails_docker/docker-compose.yml.tt
  shared/config/application.yml.tt
  shared/linters/.pronto.yml.tt
Labels: priority : normal, type : chore

#153 Refactor the template file commands
  lib/bullet.rb
  lib/config.rb
  lib/i18n.rb
  lib/linter.rb
  lib/rspec.rb
  lib/test_env.rb
  makefile
  rails_docker.rb
  shared/linters/.pronto.yml.tt
  shared/rspec/controllers/.keep
  shared/rspec/fabricators/.keep
  shared/rspec/models/.keep
  shared/rspec/requests/.keep
  shared/rspec/system/.keep
  template.rb
Labels: priority : high, type : chore

#154 Upgrade Postgresql redis image
  rails_docker/docker-compose.dev.yml.tt
  rails_docker/docker-compose.test.yml.tt
  rails_docker/docker-compose.yml.tt
  shared/config/application.yml.tt
  shared/config/database.yml
Labels: priority : low, type : chore

#157 Create api variant
  template.rb
  variants/api/app/controllers/concerns/localization.rb
  variants/api/app/template.rb
  variants/api/template.rb
Labels: priority : high, type : chore

#158 Move template related files to .template folder
  .template/addons/docker/.dockerignore.tt
  .template/addons/docker/.env.tt
  .template/addons/docker/Dockerfile.tt
  .template/addons/docker/docker-compose.dev.yml.tt
  .template/addons/docker/docker-compose.test.yml.tt
  .template/addons/docker/docker-compose.yml.tt
  .template/addons/docker/template.rb
  .template/variants/api/app/controllers/concerns/localization.rb
  .template/variants/api/app/template.rb
  .template/variants/api/template.rb
  .template/variants/web/.eslintignore
  .template/variants/web/.eslintrc
  .template/variants/web/.npmrc
  .template/variants/web/.pronto_eslint_npm.yml
  .template/variants/web/.scss-lint.yml
  .template/variants/web/Gemfile.rb
  .template/variants/web/app/assets/stylesheets/application.scss
  .template/variants/web/app/assets/stylesheets/base/.keep
  .template/variants/web/app/assets/stylesheets/components/.keep
  .template/variants/web/app/assets/stylesheets/functions/_sizing.scss
  .template/variants/web/app/assets/stylesheets/layouts/.keep
  .template/variants/web/app/assets/stylesheets/mixins/.keep
  .template/variants/web/app/assets/stylesheets/screens/.keep
  .template/variants/web/app/assets/stylesheets/variables.scss
  .template/variants/web/app/controllers/concerns/localization.rb
  .template/variants/web/app/javascript/adapters/.keep
  .template/variants/web/app/javascript/components/.keep
  .template/variants/web/app/javascript/config/.keep
  .template/variants/web/app/javascript/helpers/.keep
  .template/variants/web/app/javascript/initializers/.keep
  .template/variants/web/app/javascript/initializers/i18n.js
  .template/variants/web/app/javascript/initializers/index.js
  .template/variants/web/app/javascript/lib/.keep
  .template/variants/web/app/javascript/screens/index.js
  .template/variants/web/app/template.rb
  .template/variants/web/config/application.rb
  .template/variants/web/config/environments/test.rb
  .template/variants/web/config/i18n-js.yml
  .template/variants/web/config/template.rb
  .template/variants/web/config/webpack/environment.js.rb
  .template/variants/web/config/webpack/template.rb
  .template/variants/web/package.json.rb
  .template/variants/web/spec/codebase/codebase_spec.rb
  .template/variants/web/spec/support/assets.rb
  .template/variants/web/spec/support/capybara.rb
  .template/variants/web/spec/support/disable_animation.rb
  .template/variants/web/spec/support/system.rb
  .template/variants/web/spec/support/webdrivers.rb
  .template/variants/web/spec/system/.keep
  .template/variants/web/spec/template.rb
  .template/variants/web/template.rb
  template.rb
Labels: priority : high, type : chore

#161 Add zeitwerk checking to codebase spec
  spec/codebase/codebase_spec.rb
Labels: priority : high, type : improvement

#159 Add template tests
  .template/.rspec
  .template/.ruby-gemset
  .template/Gemfile
  .template/Gemfile.lock
  .template/addons/docker/Dockerfile.tt
  .template/spec/addons/docker/template_spec.rb
  .template/spec/base/application_spec.rb
  .template/spec/base/bin/template_spec.rb
  .template/spec/base/config/application_spec.rb
  .template/spec/base/config/environments/development_spec.rb
  .template/spec/base/config/environments/production_spec.rb
  .template/spec/base/config/environments/test_spec.rb
  .template/spec/base/config/template_spec.rb
  .template/spec/base/spec/template_spec.rb
  .template/spec/base/template_spec.rb
  .template/spec/spec_helper.rb
  .template/spec/support/serverspec.rb
  .template/spec/variants/api/template_spec.rb
  .template/spec/variants/web/app/template_spec.rb
  .template/spec/variants/web/config/application_spec.rb
  .template/spec/variants/web/config/environments/test_spec.rb
  .template/spec/variants/web/config/template_spec.rb
  .template/spec/variants/web/config/webpack/environment_js_spec.rb
  .template/spec/variants/web/docker_image_spec.rb
  .template/spec/variants/web/gemfile_spec.rb
  .template/spec/variants/web/package_json_spec.rb
  .template/spec/variants/web/spec/codebase/codebase_spec.rb
  .template/spec/variants/web/spec/template_spec.rb
  .template/spec/variants/web/template_spec.rb
  makefile
Labels: priority : normal, type : improvement

#162 Add `how to contribute` section to README file
  README.md
Labels: priority : normal, type : chore

#171 Revert "Check exit status code rather than stdout message"
  shared/rspec/codebase/codebase_spec.rb
Labels: priority : high, type : chore
