Repository nimblehq/rails-templates, pull requests merged in 2021-01, with the labels that each got.

#263 Update Rails to the latest stable version 6.1.0
  .semaphore/semaphore.yml
  Gemfile.tt
  README.md
Labels: type : feature

#267 Fix: backtrace_silencers modification does not work on the latest rails version
  config/initializers/backtrace_silencers.rb
Labels: type : bug

#268 Correct the Turbolink removal for application.js
  .template/variants/web/template.rb
Labels: type : bug

#262 Add the configuration file for rails_best_practices
  .template/spec/base/config/template_spec.rb
  config/rails_best_practices.yml
  config/template.rb
Labels: type : chore

#266 Update copyright
  LICENSE
  README.md
Labels: type : chore

#274 Allow Nginx handle incoming HTTP request on Heroku
  .template/addons/nginx/bin/start.sh
  .template/addons/nginx/config/nginx/app.conf.template.tt
  .template/spec/addons/base/nginx/template_spec.rb
Labels: type : bug

#270 Adding worker.sh
  .template/addons/heroku/Dockerfile.worker.tt
  .template/spec/base/bin/template_spec.rb
  bin/template.rb
  bin/worker.sh
Labels: type : bug

#272 Upgrade Rails version, Ruby version and Node version
  .github/workflows/test_production_build.yml
  .github/workflows/test_variants.yml
  .semaphore/semaphore.yml
  Gemfile.tt
  README.md
  template.rb
Labels: type : chore

#225 Add github actions to github addon
  .github/PULL_REQUEST_TEMPLATE.md
  .template/addons/docker/.dockerignore.tt
  .template/addons/github/.github/PULL_REQUEST_TEMPLATE.md
  .template/addons/github/.github/README.md.tt
  .template/addons/github/.github/workflows/deploy_heroku.yml.tt
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/github/.github/workflows/test_production_build.yml.tt
  .template/spec/addons/base/github/template_spec.rb
  README.md.tt
Labels: priority : high, type : feature

#275 Test doesn't run due to the NGINX configuration
  .template/addons/docker/docker-compose.test.yml.tt
  .template/addons/nginx/bin/inject_port_into_nginx.sh
  .template/addons/nginx/bin/start.sh
  .template/addons/nginx/bin/template.rb
  .template/spec/addons/base/nginx/template_spec.rb
  Makefile
Labels: priority : high, type : bug

#276 Adding `./bin/docker-prepare` into README
  README.md.tt
Labels: type : chore

#277 Make semaphoreCI addon optional
  .semaphore.yml
  .semaphore/semaphore.yml
  .template/spec/base/template_spec.rb
  Makefile
  README.md.tt
  template.rb
Labels: type : chore
