Repository nimblehq/rails-templates, pull requests merged in 2021-08, with the labels that each got.

#301 Release/4.5.0
  .template/addons/github/.github/workflows/README.md.tt
  Gemfile.tt
  README.md.tt
Labels: type : release

#298 #297 Fix: spec/support/disable_annimation.rb nil error for WebSocket requests
  .template/variants/web/spec/support/disable_animation.rb
Labels: @4.6.0, priority : low, type : bug

#302 Add the release Pull request template
  .template/addons/github/.github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
  .template/addons/github/.github/workflows/README.md.tt
  README.md.tt
Labels: type : feature
