Repository nimblehq/rails-templates, pull requests merged in 2022-07, with the labels that each got.

#329 Report Stylelint errors on the PR
  .template/addons/slim/Dangerfile.rb
  .template/spec/variants/web/dangerfile_spec.rb
  .template/spec/variants/web/gemfile_spec.rb
  .template/spec/variants/web/spec/codebase/codebase_spec.rb
  .template/variants/web/.stylelintignore
  .template/variants/web/Dangerfile.rb
  .template/variants/web/Gemfile.rb
Labels: type : feature, status : wip

#341 [#340] Update Git Template for Pull Request
  .github/PULL_REQUEST_TEMPLATE.md
  .template/addons/github/.github/PULL_REQUEST_TEMPLATE.md
Labels: type : chore

#339 [#337] Update PostgreSQL version from 12 to 14
  .template/addons/docker/docker-compose.dev.yml.tt
  .template/addons/docker/docker-compose.test.yml.tt
  config/application.yml.tt
  config/database.yml
  template.rb
Labels: type : chore

#335 fix(#334): default install_addon_prompt? to No
  template.rb
Labels: type : bug

#333 feat(#332): ability to enable hotwire
  .template/addons/hotwire/Gemfile.rb
  .template/addons/hotwire/template.rb
  .template/variants/web/Gemfile.rb
  template.rb
Labels: type : feature

#345 [#344] Fix: Test failing since the Hotwire feature
  .template/addons/hotwire/Gemfile.rb
  .template/addons/hotwire/template.rb
  .template/spec/addons/variants/web/hotwire/gemfile_spec.rb
  .template/variants/web/template.rb
  Makefile
  template.rb
Labels: type : bug

#346 [#338] Update Redis version from 5.0.7 to 6.2.7
  .template/addons/docker/docker-compose.yml.tt
  template.rb
Labels: type : chore

#347 Release/5.1.0
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .template/addons/docker/docker-compose.dev.yml.tt
  .template/addons/docker/docker-compose.test.yml.tt
  .template/addons/docker/docker-compose.yml.tt
  .template/addons/github/.github/PULL_REQUEST_TEMPLATE.md
  .template/addons/hotwire/Gemfile.rb
  .template/addons/hotwire/template.rb
  .template/addons/slim/Dangerfile.rb
  .template/spec/addons/variants/web/hotwire/gemfile_spec.rb
  .template/spec/variants/web/dangerfile_spec.rb
  .template/spec/variants/web/gemfile_spec.rb
  .template/spec/variants/web/spec/codebase/codebase_spec.rb
  .template/variants/web/.stylelintignore
  .template/variants/web/Dangerfile.rb
  .template/variants/web/Gemfile.rb
  .template/variants/web/template.rb
  Makefile
  config/application.yml.tt
  config/database.yml
  template.rb
Labels: type : release
