Repository nimblehq/rails-templates, pull requests merged in 2023-04, with the labels that each got.

#398 [#378] Feature: Convert `cancel-workflow-action` to native `concurrency`
  .github/workflows/test_generated_app.yml
  .github/workflows/test_production_build.yml
  .github/workflows/test_template.yml
  .template/addons/github/.github/workflows/deploy_heroku.yml.tt
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/github/.github/workflows/test_production_build.yml.tt
Labels: type : feature

#358 [gh-261] Use Phrase/phrase instead of PhraseApp/phraseapp/phrase_app everywhere
  .template/addons/phrase/.phrase.yml
  .template/addons/phrase/spec/codebase/codebase_spec.rb
  .template/addons/phrase/spec/template.rb
  .template/addons/phrase/template.rb
  .template/addons/phrase_app/.phraseapp.yml
  .template/addons/phrase_app/spec/codebase/codebase_spec.rb
  .template/spec/addons/base/phrase/template.rb
  .template/spec/addons/base/phrase_app/template.rb
  Makefile
  README.md
  template.rb
Labels: type : chore

#399 [#368] Remove `rails_best_practices`
  .template/spec/base/config/template_spec.rb
  Dangerfile
  Gemfile.tt
  config/rails_best_practices.yml
  config/template.rb
Labels: type : bug

#402 Release 5.5.0
  .github/workflows/test_generated_app.yml
  .github/workflows/test_production_build.yml
  .github/workflows/test_template.yml
  .template/addons/github/.github/workflows/deploy_heroku.yml.tt
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/github/.github/workflows/test_production_build.yml.tt
  .template/addons/phrase/.phrase.yml
  .template/addons/phrase/spec/codebase/codebase_spec.rb
  .template/addons/phrase/spec/template.rb
  .template/addons/phrase/template.rb
  .template/addons/phrase_app/.phraseapp.yml
  .template/addons/phrase_app/spec/codebase/codebase_spec.rb
  .template/spec/addons/base/phrase/template.rb
  .template/spec/addons/base/phrase_app/template.rb
  .template/spec/base/config/template_spec.rb
  Dangerfile
  Gemfile.tt
  Makefile
  README.md
  bin/docker-assets-precompile
  config/application.yml.tt
  config/rails_best_practices.yml
  config/template.rb
  template.rb
Labels: type : release

#359 [#348] Add Makefile to build commands
  .gitignore
  .gitignore.rb
  .rubocop.yml
  .template/addons/github/.github/workflows/test.yml.tt
  .template/variants/web/.gitignore.rb
  .template/variants/web/spec/support/capybara.rb
  Makefile.tt
  README.md
  README.md.tt
  bin/envteardown.sh
  bin/template.rb
  spec/support/vcr.rb
  template.rb
Labels: type : feature
