Repository nimblehq/rails-templates, pull requests merged in 2023-02, with the labels that each got.

#369 [#363] Fix: Remove the "Has missing safe method" check from the Danger code review
  .reek.yml
Labels: type : bug

#381 [#380] Fix: esbuild 0.17.X has different interface to implement the watch argument
  .template/variants/web/app/javascript/build.js
Labels: type : bug

#370 [#362] Fix: Rubocop prevent multi except tests
  .rubocop.yml
Labels: type : bug

#382 Release 5.3.0
  .reek.yml
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/semaphore/.semaphore/semaphore.yml.tt
  .template/spec/variants/web/package_json_spec.rb
  .template/variants/web/.stylelintrc
  .template/variants/web/app/assets/stylesheets/functions/_sizing.scss
  .template/variants/web/app/javascript/build.js
  .template/variants/web/package.json.rb
Labels: type : release

#379 [#372] Chore: Update deprecated set-output with GITHUB_OUTPUT environment file
  .github/CODEOWNERS
  .github/workflows/test_production_build.yml
  .github/workflows/test_template.yml
  .github/workflows/test_variants.yml
  .template/addons/github/.github/workflows/deploy_heroku.yml.tt
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/github/.github/workflows/test_production_build.yml.tt
  README.md.tt
Labels: type : chore

#392 [gh391] Enable TEST_RETRY on Github CI
  .template/addons/docker/.env.tt
  .template/addons/github/.github/workflows/test.yml.tt
Labels: type : feature

#377 [gh376] Separate the linting job
  .template/addons/github/.github/workflows/test.yml.tt
Labels: type : feature

#390 [#389] Update Bootstrap 5.1.3 to 5.2.3 to resolve deprecated issues
  .template/addons/bootstrap/package.json.rb
  .template/addons/bootstrap/stylesheets/vendor/_bootstrap.scss
Labels: type : feature
