Repository nimblehq/rails-templates, pull requests merged in 2023-07, with the labels that each got.

#418 [#383] Upgrade Rails version
  .github/workflows/test_generated_app.yml
  .github/workflows/test_production_build.yml
  Gemfile.tt
  README.md
Labels: type : chore

#419 [#316] Upgrade Ruby version
  .github/workflows/test_generated_app.yml
  .github/workflows/test_production_build.yml
  .github/workflows/test_template.yml
  .template/Gemfile.lock
  .template/addons/docker/Dockerfile.tt
  .template/addons/phrase/spec/codebase/codebase_spec.rb
  .template/variants/web/package.json.rb
  .tool-versions
  Gemfile.tt
  README.md
  bin/docker-assets-precompile
  template.rb
Labels: type : chore

#420 [#383] Upgrade Node and Ruby dependency versions
  .template/addons/bootstrap/package.json.rb
  .template/addons/bootstrap/stylesheets/vendor/_bootstrap.scss
  .template/addons/phrase/spec/codebase/codebase_spec.rb
  .template/variants/web/package.json.rb
  .tool-versions
  Gemfile.tt
  README.md
  spec/codebase/codebase_spec.rb
  template.rb
Labels: type : chore

#434 [#433] Add the `.keep` file
  .template/spec/variants/web/app/template_spec.rb
  .template/variants/web/app/assets/builds/.keep
  .template/variants/web/app/template.rb
Labels: type : feature

#427 Correct the build:css task
  .template/spec/variants/web/package_json_spec.rb
  .template/variants/web/Procfile.dev.rb
  .template/variants/web/app/javascript/build.js
  .template/variants/web/app/template.rb
  .template/variants/web/package.json.rb
Labels: type : bug

#435 [#430] Update the .stylelintignore - Add public/*
  .template/variants/web/.stylelintignore
Labels: type : feature

#437 [#436] Fix invalid workflow bug for publish wiki workflow
  .template/addons/github/.github/workflows/publish_wiki.yml.tt
Labels: type : bug

#432 [#223] Ignore Danger run on WIP pull request
  .template/addons/github/.github/workflows/test.yml.tt
Labels: type : improvement
