Repository nimblehq/rails-templates, pull requests merged in 2023-11, with the labels that each got.

#477 Release 5.10.0
  .template/variants/web/.gitignore.rb
  README.md.tt
Labels: type : release

#481 [#478] Fix: Duplicated `Dockerfile` and `.dockerignore` when generating the project with Rails 7.1
  .template/addons/docker/template.rb
Labels: type : bug

#479 [#473] Revise the Flow for Asking Options to generate the project
  .template/addons/openapi/template.rb
  .template/variants/web/template.rb
  Makefile
  template.rb
Labels: type : feature
