Repository nimblehq/rails-templates, pull requests merged in 2024-04, with the labels that each got.

#506 [#493][CRUD] Add the form view templates to the generator
  .template/addons/crud/lib/templates/slim/scaffold/_form.html.slim.tt
  .template/addons/crud/lib/templates/slim/scaffold/edit.html.slim.tt
  .template/addons/crud/lib/templates/slim/scaffold/new.html.slim.tt
Labels: type : feature

#504 [#357] Fix: docker compose command is not working as expected
  .github/workflows/test_generated_app.yml
  .github/workflows/test_production_build.yml
  .template/addons/docker/docker-compose.dev.yml.tt
  .template/addons/docker/docker-compose.test.yml.tt
  .template/addons/docker/docker-compose.yml.tt
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/heroku/Dockerfile.web.tt
  .template/addons/heroku/Dockerfile.worker.tt
  .template/spec/support/serverspec.rb
  .template/spec/variants/web/template_spec.rb
  .template/variants/web/.eslintignore
  .template/variants/web/eslint.config.mjs
  .template/variants/web/template.rb
  Makefile
  template.rb
Labels: type : bug, priority : high

#510 Release – 5.14.0
  .github/workflows/test_generated_app.yml
  .github/workflows/test_production_build.yml
  .template/addons/crud/lib/templates/slim/scaffold/_form.html.slim.tt
  .template/addons/crud/lib/templates/slim/scaffold/edit.html.slim.tt
  .template/addons/crud/lib/templates/slim/scaffold/new.html.slim.tt
  .template/addons/docker/docker-compose.dev.yml.tt
  .template/addons/docker/docker-compose.test.yml.tt
  .template/addons/docker/docker-compose.yml.tt
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/heroku/Dockerfile.web.tt
  .template/addons/heroku/Dockerfile.worker.tt
  .template/addons/openapi/package.json.rb
  .template/spec/addons/base/openapi/template_spec.rb
  .template/spec/support/serverspec.rb
  .template/spec/variants/web/package_json_spec.rb
  .template/spec/variants/web/template_spec.rb
  .template/variants/web/.eslintignore
  .template/variants/web/.eslintrc.tt
  .template/variants/web/eslint.config.mjs
  .template/variants/web/package.json.rb
  .template/variants/web/template.rb
  Makefile
  template.rb
Labels: type : release

#509 [#499] Create a Rubocop cop for ordering instructions in class (e.g. Models)
  .rubocop.yml
  .template/addons/custom_cops/template.rb
  rubocop/custom_cops/class_template.rb
  rubocop/custom_cops/class_template/expression_category.rb
  rubocop/spec/class_template/expression_category_spec.rb
  rubocop/spec/class_template_spec.rb
  rubocop/spec/required_inverse_of_relations_spec.rb
Labels: type : feature

#511 [#460] Revisit and set the default value for some environment variables
  .template/spec/base/config/environments/development_spec.rb
  .template/spec/base/config/environments/production_spec.rb
  .template/spec/base/config/environments/test_spec.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
Labels: type : chore
