Repository nimblehq/rails-templates, pull requests merged in 2024-01, with the labels that each got.

#496 [#463] Update the branch-tag-action in the test workflow
  .template/addons/github/.github/workflows/test.yml.tt
Labels: type : chore

#500 [#482] Add the Rubocop cop to enforce YARD documentation for public methods
  .rubocop.yml
  .template/addons/svgeez/helpers/svg_helper.rb
Labels: type : chore

#501 [#429] Revisit the test workflow
  .template/addons/github/.github/workflows/test.yml.tt
Labels: type : feature

#503 Fix Rubocop issue after merging 2 PR
  rubocop/custom_cops/required_inverse_of_relations.rb
Labels: type : bug

#502 Release - 5.12.0
  .rubocop.yml
  .template/addons/custom_cops/template.rb
  .template/addons/github/.github/workflows/test.yml.tt
  .template/addons/svgeez/helpers/svg_helper.rb
  rubocop/Gemfile
  rubocop/Gemfile.lock
  rubocop/custom_cops/required_inverse_of_relations.rb
  rubocop/spec/required_inverse_of_relations_spec.rb
  template.rb
Labels: type : release
